export const sample_foods = [
  {
    id: "1",
    name: "Jollof Rice and Chicken",
    cookTime: "30-40",
    price: 2000,
    favorite: true,
    origins: ["Senegal", "West Africa"],
    stars: 4,
    imageUrl: "food-1.jpg",
    tags: ["Rice", "Lunch", "Dinner"],
  },
  {
    id: "2",
    name: "Amala and Ewedu",
    cookTime: "60-70",
    price: 1500,
    favorite: true,
    origins: ["Nigeria"],
    stars: 4.5,
    imageUrl: "food-2.jpg",
    tags: ["Starch", "Lunch", "Dinner", "Soup"],
  },
  {
    id: "3",
    name: "Boiled Yam and Egg Sauce",
    cookTime: "20-30",
    price: 800,
    favorite: false,
    origins: ["West Africa", "Nigeria"],
    stars: 3.4,
    imageUrl: "food-3.jpg",
    tags: ["Starch", "Breakfast", "Lunch"],
  },
  {
    id: "4",
    name: "Rice and Beans",
    cookTime: "50-60",
    price: 1200,
    favorite: true,
    origins: ["Central or South America"],
    stars: 4.7,
    imageUrl: "food-4.jpg",
    tags: ["Rice", "Lunch", "Dinner"],
  },
  {
    id: "5",
    name: "MoiMoi Elewe",
    cookTime: "60-70",
    price: 500,
    favorite: false,
    origins: ["Nigeria"],
    stars: 4.3,
    imageUrl: "food-5.jpg",
    tags: ["Snack", "Breakfast"],
  },
  {
    id: "6",
    name: "Pounded Yam and Egusi Soup",
    cookTime: "60-70",
    price: 2000,
    favorite: true,
    origins: ["Nigeria"],
    stars: 5,
    imageUrl: "food-6.jpg",
    tags: ["Starch", "Soup", "Lunch", "Dinner"],
  },
];

export const sample_tags = [
  { name: "All", count: 6 },
  { name: "Starch", count: 3 },
  { name: "Lunch", count: 5 },
  { name: "Dinner", count: 4 },
  { name: "Rice", count: 2 },
  { name: "Soup", count: 2 },
  { name: "Snack", count: 1 },
  { name: "Breakfast", count: 2 },
];

export const sample_users = [
  {
    id: 1,
    name: 'John Doe',
    email: 'john@gmail.com',
    password: '12345',
    address: 'Toronto On',
    isAdmin: false,
  },
  {
    id: 2,
    name: 'Jane Doe',
    email: 'jane@gmail.com',
    password: '12345',
    address: 'Shanghai',
    isAdmin: true,
  },
];
